### ISSUE TITLE
Initial Template Doesnt work

### ISSUE THREAD

**Issue by russmartin304** [MXClyde/mendix-kubernetes-azure#2]
When running the initial template deploy i get errors on 'Add Task Group'. Gives unhandled error with code 401. If I copy out the section for adding a group and try to import the task group manually i get the following error: Import of task group failed with error TypeError: n.metaTaskInputs.map is not a function.

**Comment by MXClyde** [comment]
Most likely you are using the wrong URL on the Azure Devops API Service Connection(s). The URL needs to be the full URL to the project + /_apis, e.g.:

https://dev.azure.com/mendix-vpc-demo/Mendix-Cluster-EastUS/_apis

PS. The template has been updated today to reflect changes in Azure DevOps, so please download it again.
