### ISSUE TITLE
Error: No such container:path: mendixapp:/build/model/metadata.json

### ISSUE THREAD

**Issue by Gustav-Coleske** [MXClyde/mendix-kubernetes-azure#5]
We started getting the below error since 26 November across all the application landscape (DEV, QA and PROD - QA and PROD were taken from this git repository):

`Error: No such container:path: mendixapp:/build/model/metadata.json`
`/usr/bin/docker failed with return code 1`

It is failing on this step:
![Failed_Step](https://user-images.githubusercontent.com/29554761/70054846-354f6d00-15d0-11ea-8802-22c328581e23.png)

This is running Ubuntu 18.04.

Any idea/pointers to what may be causing this?

**Comment by MXClyde** [comment]
When this happens, typically there is an error earlier in the pipeline during the build phase. Can you check the output from that step?

**Comment by lis10** [comment]
There were no errors in any of the previous steps
![Step_Prior_2_fail](https://user-images.githubusercontent.com/17502594/70058470-f65bf000-15ac-11ea-8226-0b447b994337.png)

**Comment by lis10** [comment]
Here is the step from a "good" build
![Step_Prior_2_fail_from_last_good](https://user-images.githubusercontent.com/17502594/70058512-0bd11a00-15ad-11ea-9e14-1bf77989e85d.png)

**Comment by lis10** [comment]
All builds failed on the same date and time at the same step

**Comment by MXClyde** [comment]
Can you post the full log output of the whole build process?

**Comment by lis10** [comment]
Logs for failed build in QA
________________________________

**Comment by lis10** [comment]
In email

**Comment by Gustav-Coleske** [comment]
Confirming that this is due to outdated widgets.  One of our widgets had a dependency on the dojox libraries as part of an 8.4.0 upgrade.  We updated the widget and it worked.  An alternative would also have been to upgrade to 8.4.1, where dojox libraries are supported again.
